imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    contact: contact@openhivemanager.org
    support: support@openhivemanager.org

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

braincrafted_bootstrap:
    output_dir:
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js
    css_preprocessor: lessphp # "less", "lessphp", "sass" or "none"
    fonts_dir: %kernel.root_dir%/../web/fonts
    icon_prefix: fa
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig  
        
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
 
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ KGBeekeepingManagementBundle, KGSiteBundle, FOSUserBundle, KGUserBundle, BraincraftedBootstrapBundle ]
    #java: /usr/bin/java
    node: /usr/bin/nodejs
    #node: "C:\\Program Files\\nodejs\\node.exe"
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"            
        uglifyjs2:
            # the path to the uglifyjs executable
            bin: /usr/local/bin/uglifyjs
            #bin: "%kernel.root_dir%\\Resources\\node_modules\\uglify-js\\bin\\uglifyjs"
        uglifycss:
            bin: /usr/local/bin/uglifycss                    
            #bin: "%kernel.root_dir%\\Resources\\node_modules\\uglifycss\\uglifycss"         
                    
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
                  phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
        
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
       
# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    auth_mode: login
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:       465
    encryption: ssl
        
    #spool:     { type: memory }

sc_datetimepicker:
    picker: ~
    
fos_user:
    db_driver:     orm                       
    firewall_name: main                      
    user_class:    KG\UserBundle\Entity\User   
    registration:
        confirmation:
            enabled: true
            from_email:
                address:        "%fos_user_registration%"
                sender_name:    "%sender_name%"           
    from_email:
        address:        "%mailer_user%"
        sender_name:    "%sender_name%"    
    resetting:
        email:
            from_email:
                address:        "%fos_user_resetting%"
                sender_name:    "%sender_name%"     
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: email/password_resetting.email.twig          
            
lexik_maintenance:
    authorized:
        #path: /path                                                         # Optional. Authorized path, accepts regexs
        host: openhivemanager.org                                           # Optional. Authorized domain, accepts regexs
        ips: ['127.0.0.1', '78.239.56.74']                                  # Optional. Authorized ip addresses
        #query: { foo: bar }                                                 # Optional. Authorized request query parameter (GET/POST)
        #cookie: { bar: baz }                                                # Optional. Authorized cookie
        #route:                                                              # Optional. Authorized route name
        #attributes:                                                         # Optional. Authorized route attributes
    driver:
        #ttl: 3600                                                                  # Optional ttl option, can be not set

         # File driver
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver'                # class for file driver
        options: {file_path: %kernel.root_dir%/cache/lock}                         # file_path is the complete path for create the file

         # Shared memory driver
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\ShmDriver'                 # class for shared memory driver

         # MemCache driver
        class: Lexik\Bundle\MaintenanceBundle\Drivers\MemCacheDriver               # class for MemCache driver
        options: {key_name: 'maintenance', host: 127.0.0.1, port: 11211}           # need to define a key_name, the host and port

        # Database driver:
        class: 'Lexik\Bundle\MaintenanceBundle\Drivers\DatabaseDriver'             # class for database driver

        # Option 1 : for doctrine
        #options: {connection: custom}                                            # Optional. You can choice an other connection. Without option it's the doctrine default connection who will be used

        # Option 2 : for dsn, you must have a column ttl type datetime in your table.
        #options: {dsn: "mysql:dbname=maintenance;host:localhost", table: maintenance, user: root, password: root}  # the dsn configuration, name of table, user/password

    #Optional. response code and status of the maintenance page
    response:
        code: 503
        status: "Service Temporarily Unavailable"            
        
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations  
    
cmen_google_charts:
    version: "current"        
